title: Michael Lawrence García
email: garcia.mlawrence@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Accelerating computational mechanics with machine learning.
baseurl: "" # the subpath of your site, e.g. /blog
logo: /assets/profile-new.jpg
url: "https://garcia.ml"
github_username:  garmly

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
markdown: Kramdown
